In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [102]:
bikes = pd.read_csv("insurance.csv")
bikes

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       0  16884.92400
1      18    1  33.770         1       0       3   1725.55230
2      28    1  33.000         3       0       3   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
5      31    0  25.740         0       0       3   3756.62160
6      46    0  33.440         1       0       3   8240.58960
7      37    0  27.740         3       0       1   7281.50560
8      37    1  29.830         2       0       2   6406.41070
9      60    0  25.840         0       0       1  28923.13692
10     25    1  26.220         0       0       2   2721.32080
11     62    0  26.290         0       1       3  27808.72510
12     23    1  34.400         0       0       0   1826.84300
13     56    0  39.820         0       0       3  11090.71780
14     27    1  42.130         0       1       3  39611.75770
15     19    1  24.600         1       0       0   1837.23700
16     52    0  30.780         1       0       2  10797.33620
17     23    1  23.845         0       0       2   2395.17155
18     56    1  40.300         0       0       0  10602.38500
19     30    1  35.300         0       1       0  36837.46700
20     60    0  36.005         0       0       2  13228.84695
21     30    0  32.400         1       0       0   4149.73600
22     18    1  34.100         0       0       3   1137.01100
23     34    0  31.920         1       1       2  37701.87680
24     37    1  28.025         2       0       1   6203.90175
25     59    0  27.720         3       0       3  14001.13380
26     63    0  23.085         0       0       2  14451.83515
27     55    0  32.775         2       0       1  12268.63225
28     23    1  17.385         1       0       1   2775.19215
29     31    1  36.300         2       1       0  38711.00000
...   ...  ...     ...       ...     ...     ...          ...
1308   25    0  30.200         0       1       0  33900.65300
1309   41    1  32.200         2       0       0   6875.96100
1310   42    1  26.315         1       0       1   6940.90985
1311   33    0  26.695         0       0       1   4571.41305
1312   34    1  42.900         1       0       0   4536.25900
1313   19    0  34.700         2       1       0  36397.57600
1314   30    0  23.655         3       1       1  18765.87545
1315   18    1  28.310         1       0       2  11272.33139
1316   19    0  20.600         0       0       0   1731.67700
1317   18    1  53.130         0       0       3   1163.46270
1318   35    1  39.710         4       0       2  19496.71917
1319   39    0  26.315         2       0       1   7201.70085
1320   31    1  31.065         3       0       1   5425.02335
1321   62    1  26.695         0       1       2  28101.33305
1322   62    1  38.830         0       0       3  12981.34570
1323   42    0  40.370         2       1       3  43896.37630
1324   31    1  25.935         1       0       1   4239.89265
1325   61    1  33.535         0       0       2  13143.33665
1326   42    0  32.870         0       0       2   7050.02130
1327   51    1  30.030         1       0       3   9377.90470
1328   23    0  24.225         2       0       2  22395.74424
1329   52    1  38.600         2       0       0  10325.20600
1330   57    0  25.740         2       0       3  12629.16560
1331   23    0  33.400         0       0       0  10795.93733
1332   52    0  44.700         3       0       0  11411.68500
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       2   2205.98080
1335   18    0  36.850         0       0       3   1629.83350
1336   21    0  25.800         0       0       0   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [126]:
from numpy import genfromtxt
bikes = genfromtxt('insurance.csv', delimiter=',')

# np.random.shuffle(bikes)

X = bikes[1:,0:6]
Y = bikes[1:,[6]]

print(X)
print(Y)

[[19.    0.   27.9   0.    1.    0.  ]
 [18.    1.   33.77  1.    0.    3.  ]
 [28.    1.   33.    3.    0.    3.  ]
 ...
 [18.    0.   36.85  0.    0.    3.  ]
 [21.    0.   25.8   0.    0.    0.  ]
 [61.    0.   29.07  0.    1.    1.  ]]
[[16884.924 ]
 [ 1725.5523]
 [ 4449.462 ]
 ...
 [ 1629.8335]
 [ 2007.945 ]
 [29141.3603]]

In [135]:
for cont in range(6):
    X[:,cont] = ((X[:,cont]-X[:,cont].min())/(X[:,cont].max()-X[:,cont].min()))
    
for cont in range(1):
    Y[:,cont] = (Y[:,cont]/(Y[:,cont].max()))
    
print(X)
print(Y)

[[0.02173913 0.         0.3212268  0.         1.         0.        ]
 [0.         1.         0.47914985 0.2        0.         1.        ]
 [0.2173913  1.         0.45843422 0.6        0.         1.        ]
 ...
 [0.         0.         0.56201238 0.         0.         1.        ]
 [0.06521739 0.         0.26472962 0.         0.         0.        ]
 [0.93478261 0.         0.35270379 0.         1.         0.33333333]]
[[0.26477671]
 [0.02705882]
 [0.06977312]
 ...
 [0.02555783]
 [0.03148709]
 [0.45697295]]

In [128]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(6, activation=tf.nn.relu),
  tf.keras.layers.Dense(7, activation=tf.nn.relu),
  tf.keras.layers.Dense(1, activation=tf.nn.sigmoid)
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [137]:
model.fit(X, Y, epochs=15)

Epoch 1/15
1338/1338 [==============================] - 0s 66us/step - loss: 0.4287 - acc: 7.4738e-04
Epoch 2/15
1338/1338 [==============================] - 0s 71us/step - loss: 0.4287 - acc: 7.4738e-04
Epoch 3/15
1338/1338 [==============================] - 0s 65us/step - loss: 0.4287 - acc: 7.4738e-04
Epoch 4/15
1338/1338 [==============================] - 0s 67us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 5/15
1338/1338 [==============================] - 0s 68us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 6/15
1338/1338 [==============================] - 0s 65us/step - loss: 0.4288 - acc: 7.4738e-04
Epoch 7/15
1338/1338 [==============================] - 0s 65us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 8/15
1338/1338 [==============================] - ETA: 0s - loss: 0.4303 - acc: 0.0000e+0 - 0s 64us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 9/15
1338/1338 [==============================] - 0s 70us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 10/15
1338/1338 [==============================] - 0s 70us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 11/15
1338/1338 [==============================] - 0s 70us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 12/15
1338/1338 [==============================] - 0s 82us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 13/15
1338/1338 [==============================] - 0s 68us/step - loss: 0.4287 - acc: 7.4738e-04
Epoch 14/15
1338/1338 [==============================] - 0s 67us/step - loss: 0.4286 - acc: 7.4738e-04
Epoch 15/15
1338/1338 [==============================] - 0s 66us/step - loss: 0.4286 - acc: 7.4738e-04

In [130]:
scores = model.evaluate(X, Y)
print(scores)

1338/1338 [==============================] - 1s 472us/step
[0.42838452727448956, 0.0007473841554559044]

In [138]:
scores = model.predict(X)
print(scores)

[[0.34610546]
 [0.05408736]
 [0.09936287]
 ...
 [0.04978273]
 [0.05380865]
 [0.5482893 ]]

In [132]:
print(Y)

[[0.26477671]
 [0.02705882]
 [0.06977312]
 ...
 [0.02555783]
 [0.03148709]
 [0.45697295]]